### ISSUE TITLE
Expose result of mosquitto_loop_forever

### ISSUE THREAD

**Issue by jbwdevries** [tolysz/c-mosquitto#10]
Basically, loop_forever can return an error (either a code or a string via `strerror_r`). If it returns, you can't see why it did.

**Comment by tolysz** [comment]
Do you have a suggestion how to fix it? If you could propose a solution (ideally with a different name if you change the type) I can merge it.

**Comment by jbwdevries** [comment]
I have created PR that would solve the issue I think
