### ISSUE TITLE
Username + Password authentication via TLS not possible

### ISSUE THREAD

**Issue by asciijungle** [tolysz/c-mosquitto#8]
Hi Folks,

thanks for your efforts in building and maintaining this library.
I'd like to use TLS with username and password authentication against a broker. As I'm not using self signed certificates I'm not able to generate a client certificate that I could use.
libmosquitto supports this by setting `keyfile` and `certfile` to `NULL` in `mosquitto_tls_set` according to the documentation: https://mosquitto.org/api/files/mosquitto-h.html#mosquitto_tls_set
c-mosquitto however does not allow me to feed `NULL` into 
```
setTls :: Mosquitto a -> String -> String -> String -> IO ()
```
since Strings are not nullable in Haskell.

I could imagine the following solution:
```
Mosquitto.TlsConfig = ClientCertificateConfig String String String | CaOnlyConfig String

setTls :: Mosquitto a -> Mosquitto.TlsConfig -> IO ()
```
Unfortunately that would be a breaking API change. What's your opinion on that?
Best Regards

**Comment by tolysz** [comment]
It should be fixed in the version  0.1.5.0

**Comment by asciijungle** [comment]
cool thanks!

**Comment by tolysz** [comment]
It is now possible with:
`setTlsNoClientCert + setUsernamePassword`
